language: common-lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t:examples
  matrix:
    - LISP="sbcl-bin --dynamic-space-size 2048" COVERALLS=true

services:
  - rabbitmq
    
before_install:
  - sudo apt-get install -y libfixposix-dev
  - sudo apt-get install -y libffi-dev
  - sudo apt-get install libssl-dev

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros install prove

before_script:
  - ./install-travis-deps.sh

script:
  - run-prove cl-bunny.test.asd